// <auto-generated />
using System;
using CompanySystem.DAL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DAL.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260404001642_first")]
    partial class first
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CompanySystem.DAL.ApplicationRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "role-admin-guid-0001",
                            ConcurrencyStamp = "role-admin-stamp-0001",
                            Description = "Full system access",
                            Name = "Admin",
                            NormalizedName = "ADMIN"
                        },
                        new
                        {
                            Id = "role-user-guid-0002",
                            ConcurrencyStamp = "role-user-stamp-0002",
                            Description = "Read-only access",
                            Name = "User",
                            NormalizedName = "USER"
                        });
                });

            modelBuilder.Entity("CompanySystem.DAL.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "user-admin-guid-0001",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "admin-concurrency-stamp-fixed",
                            CreatedAt = new DateTime(2026, 3, 1, 10, 30, 0, 0, DateTimeKind.Unspecified),
                            Email = "admin@company.com",
                            EmailConfirmed = true,
                            FirstName = "System",
                            LastName = "Admin",
                            LockoutEnabled = false,
                            NormalizedEmail = "ADMIN@COMPANY.COM",
                            NormalizedUserName = "ADMIN",
                            PasswordHash = "AQAAAAIAAYagAAAAEDkIZ0tcFEeu7jIpN95iNUAh2tk+s8EaF81lOQZJk24GQpewc8gAAyJRo/hG9mp/DA==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "admin-security-stamp-fixed",
                            TwoFactorEnabled = false,
                            UserName = "admin"
                        });
                });

            modelBuilder.Entity("CompanySystem.DAL.Cart", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Carts");
                });

            modelBuilder.Entity("CompanySystem.DAL.CartItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CartId")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("CartId", "ProductId")
                        .IsUnique();

                    b.ToTable("CartItems");
                });

            modelBuilder.Entity("CompanySystem.DAL.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageURL")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Slug")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 3, 1, 10, 30, 0, 0, DateTimeKind.Unspecified),
                            Description = "Seasonal fresh fruits full of natural sweetness and vitamins.",
                            ImageURL = "https://images.unsplash.com/photo-1610832958506-aa56368176cf?w=400&h=300&fit=crop",
                            Name = "Fresh Fruits",
                            Slug = "fresh-fruits"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 3, 1, 10, 30, 0, 0, DateTimeKind.Unspecified),
                            Description = "Farm-fresh vegetables for healthy everyday meals.",
                            ImageURL = "https://images.unsplash.com/photo-1542838132-92c53300491e?w=400&h=300&fit=crop",
                            Name = "Vegetables",
                            Slug = "vegetables"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2026, 3, 1, 10, 30, 0, 0, DateTimeKind.Unspecified),
                            Description = "Fresh aromatic herbs and leafy greens for everyday cooking.",
                            ImageURL = "https://planningagarden.com/wp-content/uploads/2023/02/image-3.jpeg",
                            Name = "Herbs & Green",
                            Slug = "herbs-greens"
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2026, 3, 1, 10, 30, 0, 0, DateTimeKind.Unspecified),
                            Description = "Premium quality dried fruits full of natural sweetness.",
                            ImageURL = "https://d2jx2rerrg6sh3.cloudfront.net/images/news/ImageForNews_785204_17210137222997757.jpg",
                            Name = "Dried Fruits",
                            Slug = "dried-fruits"
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2026, 3, 1, 10, 30, 0, 0, DateTimeKind.Unspecified),
                            Description = "Sun-dried vegetables for long-lasting freshness and flavor.",
                            ImageURL = "https://tse4.mm.bing.net/th/id/OIP.h-BRxUaPTE40ulRlQ1PlUQHaE8?w=900&h=600&rs=1&pid=ImgDetMain&o=7&rm=3",
                            Name = "Dried Vegetables",
                            Slug = "dried-vegetables"
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2026, 3, 1, 10, 30, 0, 0, DateTimeKind.Unspecified),
                            Description = "Premium nuts and seeds for healthy snacking.",
                            ImageURL = "https://img.freepik.com/premium-photo/top-view-composition-assorted-nuts-creating-natural-background-with-various-types-nuts_174533-37574.jpg?w=2000",
                            Name = "Nuts",
                            Slug = "nuts"
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2026, 3, 1, 10, 30, 0, 0, DateTimeKind.Unspecified),
                            Description = "Pre-prepared ingredients for quick and easy meals.",
                            ImageURL = "https://images.unsplash.com/photo-1547592180-85f173990554?w=400&h=300&fit=crop",
                            Name = "Ready to Cook",
                            Slug = "ready-to-cook"
                        },
                        new
                        {
                            Id = 8,
                            CreatedAt = new DateTime(2026, 3, 1, 10, 30, 0, 0, DateTimeKind.Unspecified),
                            Description = "Pre-cut and washed vegetables ready to use instantly.",
                            ImageURL = "https://images.unsplash.com/photo-1512621776951-a57141f2eefd?w=400&h=300&fit=crop",
                            Name = "Ready-to-use Vegetables",
                            Slug = "ready-to-use-vegetables"
                        });
                });

            modelBuilder.Entity("CompanySystem.DAL.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("PaymentMethod")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ShippingAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ShippingCity")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ShippingCountry")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ShippingFullName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ShippingPhone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("CompanySystem.DAL.OrderItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductId");

                    b.ToTable("OrderItems");
                });

            modelBuilder.Entity("CompanySystem.DAL.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<int>("Count")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageURL")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsFeatured")
                        .HasColumnType("bit");

                    b.Property<bool>("IsOrganic")
                        .HasColumnType("bit");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<double>("Rating")
                        .HasColumnType("float");

                    b.Property<int>("Reviews")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Unit")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 101,
                            CategoryId = 1,
                            Count = 150,
                            CreatedAt = new DateTime(2026, 3, 1, 10, 30, 0, 0, DateTimeKind.Unspecified),
                            Description = "Crisp and juicy red apples, full of natural sweetness and vitamins.",
                            ImageURL = "https://images.unsplash.com/photo-1567306226416-28f0efdc88ce?w=400&h=400&fit=crop",
                            IsFeatured = false,
                            IsOrganic = true,
                            Price = 3.49m,
                            Rating = 4.7000000000000002,
                            Reviews = 120,
                            Title = "Red Apple",
                            Unit = "kg"
                        },
                        new
                        {
                            Id = 102,
                            CategoryId = 1,
                            Count = 200,
                            CreatedAt = new DateTime(2026, 3, 1, 10, 30, 0, 0, DateTimeKind.Unspecified),
                            Description = "Ripe yellow bananas, naturally sweet and packed with potassium.",
                            ImageURL = "https://images.unsplash.com/photo-1571771894821-ce9b6c11b08e?w=400&h=400&fit=crop",
                            IsFeatured = false,
                            IsOrganic = false,
                            Price = 2.49m,
                            Rating = 4.5999999999999996,
                            Reviews = 89,
                            Title = "Banana",
                            Unit = "bunch"
                        },
                        new
                        {
                            Id = 103,
                            CategoryId = 1,
                            Count = 90,
                            CreatedAt = new DateTime(2026, 3, 1, 10, 30, 0, 0, DateTimeKind.Unspecified),
                            Description = "Sweet and ripe strawberries, perfect for desserts or smoothies.",
                            ImageURL = "https://diyhomedesignideas.com/photos/800-webp/e2fo8m6o1bxd5lpsfn0q.webp",
                            IsFeatured = true,
                            IsOrganic = true,
                            Price = 5.99m,
                            Rating = 4.7999999999999998,
                            Reviews = 95,
                            Title = "Strawberries",
                            Unit = "kg"
                        },
                        new
                        {
                            Id = 104,
                            CategoryId = 1,
                            Count = 120,
                            CreatedAt = new DateTime(2026, 3, 1, 10, 30, 0, 0, DateTimeKind.Unspecified),
                            Description = "Juicy green grapes, naturally sweet and perfect for snacking.",
                            ImageURL = "https://dpof9ma0om0c1.cloudfront.net/images/content-images/green-grape-landing/green-grape-header-2.jpg",
                            IsFeatured = true,
                            IsOrganic = false,
                            Price = 4.99m,
                            Rating = 4.5,
                            Reviews = 76,
                            Title = "Green Grapes",
                            Unit = "kg"
                        },
                        new
                        {
                            Id = 105,
                            CategoryId = 1,
                            Count = 50,
                            CreatedAt = new DateTime(2026, 3, 1, 10, 30, 0, 0, DateTimeKind.Unspecified),
                            Description = "Tropical pineapple, sweet, juicy and rich in vitamin C.",
                            ImageURL = "https://tse4.mm.bing.net/th/id/OIP.8Oc8ua0K7P84PpoJCP4JkQHaFj?rs=1&pid=ImgDetMain&o=7&rm=3",
                            IsFeatured = false,
                            IsOrganic = true,
                            Price = 6.49m,
                            Rating = 4.7000000000000002,
                            Reviews = 65,
                            Title = "Pineapple",
                            Unit = "piece"
                        },
                        new
                        {
                            Id = 201,
                            CategoryId = 2,
                            Count = 180,
                            CreatedAt = new DateTime(2026, 3, 1, 10, 30, 0, 0, DateTimeKind.Unspecified),
                            Description = "Fresh farm-grown carrots, crunchy and full of beta-carotene.",
                            ImageURL = "https://tse2.mm.bing.net/th/id/OIP.EOafQATWNirsC4jeS2vPHgHaFj?rs=1&pid=ImgDetMain&o=7&rm=3",
                            IsFeatured = false,
                            IsOrganic = true,
                            Price = 1.99m,
                            Rating = 4.5,
                            Reviews = 75,
                            Title = "Carrots",
                            Unit = "kg"
                        },
                        new
                        {
                            Id = 202,
                            CategoryId = 2,
                            Count = 100,
                            CreatedAt = new DateTime(2026, 3, 1, 10, 30, 0, 0, DateTimeKind.Unspecified),
                            Description = "Fresh green broccoli, perfect for steaming, stir-fry, or salads.",
                            ImageURL = "https://tse3.mm.bing.net/th/id/OIP.NN02CpCK__5Di9H_CJS_PgHaFj?w=1200&h=900&rs=1&pid=ImgDetMain&o=7&rm=3",
                            IsFeatured = false,
                            IsOrganic = true,
                            Price = 3.29m,
                            Rating = 4.5999999999999996,
                            Reviews = 88,
                            Title = "Broccoli",
                            Unit = "kg"
                        },
                        new
                        {
                            Id = 203,
                            CategoryId = 2,
                            Count = 140,
                            CreatedAt = new DateTime(2026, 3, 1, 10, 30, 0, 0, DateTimeKind.Unspecified),
                            Description = "Ripe and juicy tomatoes, perfect for salads, sauces, and cooking.",
                            ImageURL = "https://th.bing.com/th/id/R.5c476c3ea45bcf53cabd9d13aaae0b1f?rik=VNyQZ4Mhh%2bP8bg&riu=http%3a%2f%2fwww.primallyinspired.com%2fwp-content%2fuploads%2f2013%2f07%2ftomatoes.jpg&ehk=rGYZXIgLoY8HrJ1%2bPlt4DNyTW9CTf%2ftNIJ7LC0TFBFY%3d&risl=&pid=ImgRaw&r=0",
                            IsFeatured = true,
                            IsOrganic = false,
                            Price = 2.79m,
                            Rating = 4.7000000000000002,
                            Reviews = 110,
                            Title = "Tomatoes",
                            Unit = "kg"
                        },
                        new
                        {
                            Id = 204,
                            CategoryId = 2,
                            Count = 130,
                            CreatedAt = new DateTime(2026, 3, 1, 10, 30, 0, 0, DateTimeKind.Unspecified),
                            Description = "Fresh and crunchy cucumbers, perfect for salads and snacking.",
                            ImageURL = "https://tse1.mm.bing.net/th/id/OIP.S0XqwAyhE10j_4S4wAiMdAHaHa?w=600&h=600&rs=1&pid=ImgDetMain&o=7&rm=3",
                            IsFeatured = false,
                            IsOrganic = false,
                            Price = 1.89m,
                            Rating = 4.4000000000000004,
                            Reviews = 64,
                            Title = "Cucumbers",
                            Unit = "kg"
                        },
                        new
                        {
                            Id = 205,
                            CategoryId = 2,
                            Count = 80,
                            CreatedAt = new DateTime(2026, 3, 1, 10, 30, 0, 0, DateTimeKind.Unspecified),
                            Description = "Colorful bell peppers, sweet, crunchy, and full of vitamin C.",
                            ImageURL = "https://png.pngtree.com/thumb_back/fw800/background/20221014/pngtree-bell-peppers-stem-yellow-bell-pepper-photo-image_7085716.jpg",
                            IsFeatured = true,
                            IsOrganic = true,
                            Price = 3.99m,
                            Rating = 4.7999999999999998,
                            Reviews = 90,
                            Title = "Bell Peppers",
                            Unit = "kg"
                        },
                        new
                        {
                            Id = 301,
                            CategoryId = 3,
                            Count = 100,
                            CreatedAt = new DateTime(2026, 3, 1, 10, 30, 0, 0, DateTimeKind.Unspecified),
                            Description = "Aromatic fresh basil leaves, perfect for Italian dishes and pesto.",
                            ImageURL = "https://static.africaimages.com/photos/g/z/gzo9ijcch7FQo12xKmE3bquIX/gzo9ijcch7FQo12xKmE3bquIX_normal.jpg",
                            IsFeatured = false,
                            IsOrganic = true,
                            Price = 2.99m,
                            Rating = 4.7999999999999998,
                            Reviews = 89,
                            Title = "Fresh Basil",
                            Unit = "bunch"
                        },
                        new
                        {
                            Id = 302,
                            CategoryId = 3,
                            Count = 120,
                            CreatedAt = new DateTime(2026, 3, 1, 10, 30, 0, 0, DateTimeKind.Unspecified),
                            Description = "Fresh leafy spinach, perfect for salads, soups, and smoothies.",
                            ImageURL = "https://tse1.mm.bing.net/th/id/OIP.LOtuDfEdBmvLw1fu6O5qKwHaHa?rs=1&pid=ImgDetMain&o=7&rm=3",
                            IsFeatured = true,
                            IsOrganic = true,
                            Price = 2.29m,
                            Rating = 4.7999999999999998,
                            Reviews = 98,
                            Title = "Spinach",
                            Unit = "bunch"
                        },
                        new
                        {
                            Id = 303,
                            CategoryId = 3,
                            Count = 90,
                            CreatedAt = new DateTime(2026, 3, 1, 10, 30, 0, 0, DateTimeKind.Unspecified),
                            Description = "Fresh parsley, perfect for garnishing and adding flavor to any dish.",
                            ImageURL = "https://www.goodtastingmeals.com/wp-content/uploads/2021/10/what-does-parsley-taste-like.jpg",
                            IsFeatured = false,
                            IsOrganic = false,
                            Price = 1.99m,
                            Rating = 4.7000000000000002,
                            Reviews = 70,
                            Title = "Parsley",
                            Unit = "bunch"
                        },
                        new
                        {
                            Id = 304,
                            CategoryId = 3,
                            Count = 85,
                            CreatedAt = new DateTime(2026, 3, 1, 10, 30, 0, 0, DateTimeKind.Unspecified),
                            Description = "Fresh cilantro, great for salads, salsas, and soups.",
                            ImageURL = "https://cdn11.bigcommerce.com/s-jmzfi5zcr2/products/1009/images/16162/Santo_Cilantro_Plant_Leaves__77445.1644445129.500.750.jpg?c=2",
                            IsFeatured = false,
                            IsOrganic = true,
                            Price = 2.19m,
                            Rating = 4.5999999999999996,
                            Reviews = 65,
                            Title = "Cilantro",
                            Unit = "bunch"
                        },
                        new
                        {
                            Id = 401,
                            CategoryId = 4,
                            Count = 60,
                            CreatedAt = new DateTime(2026, 3, 1, 10, 30, 0, 0, DateTimeKind.Unspecified),
                            Description = "Premium Medjool dates, naturally sweet and packed with fiber.",
                            ImageURL = "https://th.bing.com/th/id/R.cb34397905d881db71e5efda819bd95a?rik=XraiGTjqYttXxg&riu=http%3a%2f%2fshop.goodhillfarms.com%2fcdn%2fshop%2ffiles%2fmedjool-dates-good-hill-farms-52898976530802.jpg%3fv%3d1742750784&ehk=qwmBPAexReYtZGyjmT0a5ZlwvRlaySAlyZJkpN0rlKw%3d&risl=&pid=ImgRaw&r=0",
                            IsFeatured = false,
                            IsOrganic = true,
                            Price = 12.99m,
                            Rating = 4.9000000000000004,
                            Reviews = 234,
                            Title = "Medjool Dates",
                            Unit = "500g"
                        },
                        new
                        {
                            Id = 402,
                            CategoryId = 4,
                            Count = 80,
                            CreatedAt = new DateTime(2026, 3, 1, 10, 30, 0, 0, DateTimeKind.Unspecified),
                            Description = "Soft and sweet dried figs, great for snacking and baking.",
                            ImageURL = "https://tse3.mm.bing.net/th/id/OIP.hT1lbtyS9Pr-RYYnuOpC7wHaHa?rs=1&pid=ImgDetMain&o=7&rm=3",
                            IsFeatured = false,
                            IsOrganic = true,
                            Price = 10.49m,
                            Rating = 4.7000000000000002,
                            Reviews = 145,
                            Title = "Dried Figs",
                            Unit = "500g"
                        },
                        new
                        {
                            Id = 403,
                            CategoryId = 4,
                            Count = 120,
                            CreatedAt = new DateTime(2026, 3, 1, 10, 30, 0, 0, DateTimeKind.Unspecified),
                            Description = "Sweet dried raisins, perfect for cereals, baking, or snacking.",
                            ImageURL = "https://th.bing.com/th/id/R.0e12c5914bc7ddf8d9ca1f9eff463f91?rik=%2bqZYk%2fisddFX4w&pid=ImgRaw&r=0",
                            IsFeatured = true,
                            IsOrganic = false,
                            Price = 6.99m,
                            Rating = 4.5999999999999996,
                            Reviews = 90,
                            Title = "Raisins",
                            Unit = "500g"
                        },
                        new
                        {
                            Id = 501,
                            CategoryId = 5,
                            Count = 50,
                            CreatedAt = new DateTime(2026, 3, 1, 10, 30, 0, 0, DateTimeKind.Unspecified),
                            Description = "Intense flavor sun-dried tomatoes, perfect for pasta and sauces.",
                            ImageURL = "https://veganwithgusto.com/wp-content/uploads/2022/08/sun-dried-tomatoes-in-bowl.jpg",
                            IsFeatured = false,
                            IsOrganic = true,
                            Price = 8.99m,
                            Rating = 4.5,
                            Reviews = 70,
                            Title = "Sun-Dried Tomatoes",
                            Unit = "250g"
                        },
                        new
                        {
                            Id = 502,
                            CategoryId = 5,
                            Count = 40,
                            CreatedAt = new DateTime(2026, 3, 1, 10, 30, 0, 0, DateTimeKind.Unspecified),
                            Description = "Crunchy dried bell peppers, great for soups, stews, and sauces.",
                            ImageURL = "https://m.media-amazon.com/images/I/71lcWW2OoIL._SL1014_.jpg",
                            IsFeatured = false,
                            IsOrganic = false,
                            Price = 7.49m,
                            Rating = 4.4000000000000004,
                            Reviews = 50,
                            Title = "Dried Bell Peppers",
                            Unit = "250g"
                        },
                        new
                        {
                            Id = 601,
                            CategoryId = 6,
                            Count = 115,
                            CreatedAt = new DateTime(2026, 3, 1, 10, 30, 0, 0, DateTimeKind.Unspecified),
                            Description = "Premium raw almonds, perfect for snacking and baking.",
                            ImageURL = "https://images.unsplash.com/photo-1508061253366-f7da158b6d46?w=400&h=400&fit=crop",
                            IsFeatured = false,
                            IsOrganic = true,
                            Price = 14.99m,
                            Rating = 4.9000000000000004,
                            Reviews = 267,
                            Title = "Raw Almonds",
                            Unit = "500g"
                        },
                        new
                        {
                            Id = 602,
                            CategoryId = 6,
                            Count = 100,
                            CreatedAt = new DateTime(2026, 3, 1, 10, 30, 0, 0, DateTimeKind.Unspecified),
                            Description = "Delicious cashews, perfect for snacking or cooking.",
                            ImageURL = "https://tse3.mm.bing.net/th/id/OIP.99BTuSASnXhpplED3C09iwHaEJ?rs=1&pid=ImgDetMain&o=7&rm=3",
                            IsFeatured = false,
                            IsOrganic = false,
                            Price = 16.49m,
                            Rating = 4.7999999999999998,
                            Reviews = 200,
                            Title = "Cashews",
                            Unit = "500g"
                        },
                        new
                        {
                            Id = 603,
                            CategoryId = 6,
                            Count = 80,
                            CreatedAt = new DateTime(2026, 3, 1, 10, 30, 0, 0, DateTimeKind.Unspecified),
                            Description = "Fresh and crunchy walnuts, ideal for baking and healthy snacks.",
                            ImageURL = "https://tse1.mm.bing.net/th/id/OIP.xHBI6PUlSitRSmQk1mobzgHaEJ?rs=1&pid=ImgDetMain&o=7&rm=3",
                            IsFeatured = true,
                            IsOrganic = true,
                            Price = 18.99m,
                            Rating = 4.7000000000000002,
                            Reviews = 150,
                            Title = "Walnuts",
                            Unit = "500g"
                        },
                        new
                        {
                            Id = 701,
                            CategoryId = 7,
                            Count = 60,
                            CreatedAt = new DateTime(2026, 3, 1, 10, 30, 0, 0, DateTimeKind.Unspecified),
                            Description = "Pre-cut vegetables ready for a quick and healthy stir-fry meal.",
                            ImageURL = "https://tse4.mm.bing.net/th/id/OIP._dpP6W5MUeTHtp6wXaabYAHaHa?rs=1&pid=ImgDetMain&o=7&rm=3",
                            IsFeatured = false,
                            IsOrganic = false,
                            Price = 5.99m,
                            Rating = 4.5999999999999996,
                            Reviews = 55,
                            Title = "Vegetable Stir-Fry Mix",
                            Unit = "pack"
                        },
                        new
                        {
                            Id = 702,
                            CategoryId = 7,
                            Count = 40,
                            CreatedAt = new DateTime(2026, 3, 1, 10, 30, 0, 0, DateTimeKind.Unspecified),
                            Description = "All ingredients pre-measured and ready for a quick chicken curry.",
                            ImageURL = "https://tse2.mm.bing.net/th/id/OIP.kEWDhQr7To2BE6NZtYyQEgHaLH?rs=1&pid=ImgDetMain&o=7&rm=3",
                            IsFeatured = false,
                            IsOrganic = true,
                            Price = 9.99m,
                            Rating = 4.7000000000000002,
                            Reviews = 60,
                            Title = "Chicken Curry Kit",
                            Unit = "kit"
                        },
                        new
                        {
                            Id = 801,
                            CategoryId = 8,
                            Count = 80,
                            CreatedAt = new DateTime(2026, 3, 1, 10, 30, 0, 0, DateTimeKind.Unspecified),
                            Description = "A mix of pre-cut and washed vegetables ready to use instantly.",
                            ImageURL = "https://img.freepik.com/premium-photo/variety-chopped-vegetables-ready-stew-created-with-generative-ai_419341-56888.jpg",
                            IsFeatured = true,
                            IsOrganic = false,
                            Price = 4.99m,
                            Rating = 4.2999999999999998,
                            Reviews = 45,
                            Title = "Pre-Cut Mixed Veggies",
                            Unit = "pack"
                        },
                        new
                        {
                            Id = 802,
                            CategoryId = 8,
                            Count = 60,
                            CreatedAt = new DateTime(2026, 3, 1, 10, 30, 0, 0, DateTimeKind.Unspecified),
                            Description = "Freshly washed and cut carrots, ready to add to any dish.",
                            ImageURL = "https://img.freepik.com/premium-photo/background-features-sliced-carrots_961875-393364.jpg",
                            IsFeatured = false,
                            IsOrganic = true,
                            Price = 3.49m,
                            Rating = 4.5,
                            Reviews = 40,
                            Title = "Pre-Cut Carrots",
                            Unit = "pack"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = "user-admin-guid-0001",
                            RoleId = "role-admin-guid-0001"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("CompanySystem.DAL.Cart", b =>
                {
                    b.HasOne("CompanySystem.DAL.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("CompanySystem.DAL.CartItem", b =>
                {
                    b.HasOne("CompanySystem.DAL.Cart", "Cart")
                        .WithMany("Items")
                        .HasForeignKey("CartId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CompanySystem.DAL.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Cart");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("CompanySystem.DAL.Order", b =>
                {
                    b.HasOne("CompanySystem.DAL.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("CompanySystem.DAL.OrderItem", b =>
                {
                    b.HasOne("CompanySystem.DAL.Order", "Order")
                        .WithMany("Items")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CompanySystem.DAL.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("CompanySystem.DAL.Product", b =>
                {
                    b.HasOne("CompanySystem.DAL.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("CompanySystem.DAL.ApplicationRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("CompanySystem.DAL.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("CompanySystem.DAL.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("CompanySystem.DAL.ApplicationRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CompanySystem.DAL.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("CompanySystem.DAL.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CompanySystem.DAL.Cart", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("CompanySystem.DAL.Category", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("CompanySystem.DAL.Order", b =>
                {
                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
